blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed
app_name = 'blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('single/<int:post_id>', views.BlogSingleView.as_view(), name='blog_single'),
    path('category/<str:cat_name>', views.BlogView.as_view(), name='blog_category'),
    path('author/<str:author_username>', views.BlogView.as_view(), name='blog_author'),
    path('tag/<str:tag_name>', views.BlogView.as_view(), name='blog_tag'),
    path('search/', views.BlogSearchView.as_view(), name='blog_search'),
    path("rss/feed/", LatestEntriesFeed()),

]

djangoProject5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('newsletter/', views.NewsLetterView.as_view(), name='newsletter'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='blog/', default='blog/feature-img2.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def count_comments(self):
        return self.comment_post.filter(approved=True).count()

    def  get_absolute_url(self):
        return reverse('blog:blog_single', kwargs={'post_id': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return f'{self.name} left a comment for post {self.post}'

blog/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'subject', 'message']

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .forms import *
from .models import *
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogView(View):
    def get(self, request, cat_name=None, author_username=None, tag_name=None):

        posts = Post.objects.filter(status=1).order_by('-published_date')
        posts_all = posts
        if cat_name:
            posts = posts.filter(category__name=cat_name)
        if author_username:
            posts = posts.filter(author__username=author_username)
        if tag_name:
            posts = posts.filter(tags__name__in=[tag_name])
        # pagination
        posts = Paginator(posts, 3)
        page_number = request.GET.get('page')
        try:
            posts = posts.get_page(page_number)
        except PageNotAnInteger:
            posts = posts.get_page(1)
        except EmptyPage:
            posts = posts.get_page(posts.num_pages)
        # section post category in html
        categories = Category.objects.all()
        cat_dict = {}
        for name in categories:
            cat_dict[name] = posts_all.filter(category=name).count()
        context = {'posts': posts,
                   'lasted_posts': posts_all[:min(4, len(posts_all))],
                   'cat_dict': cat_dict}
        return render(request, 'blog/blog-home.html', context)


class BlogSingleView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, status=1, id=post_id)
        # section latest posts
        posts = Post.objects.filter(status=1).order_by('-published_date')
        # comments post
        comments = Comment.objects.filter(post=post, approved=True)
        # show form
        form = CommentForm()
        # section post category in html
        cat_dict = {}
        categories = Category.objects.all()
        for name in categories:
            cat_dict[name] = posts.filter(category=name).count()
        context = {'post': post,
                   'lasted_posts': posts[:min(4, len(posts))],
                   'cat_dict': cat_dict,
                   'comments': comments,
                   'form': form}
        return render(request, 'blog/blog-single.html', context)

    def post(self, request, post_id):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, status=1, id=post_id)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, 'your comment submitted successfully')
        else:
            messages.error(request, 'your comment didnt submitted ')
        return redirect('blog:blog_single', post_id)


class BlogSearchView(View):
    def get(self, request):
        search = request.GET.get('search')
        posts = Post.objects.filter(status=1, content__contains=search)
        # section post category in html
        cat_dict = {}
        categories = Category.objects.all()
        for name in categories:
            cat_dict[name] = Post.objects.filter(status=1, category=name).count()
        context = {'posts': posts,
                   'cat_dict': cat_dict}
        return render(request, 'blog/blog-home.html', context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <style>
        .category {
            color: inherit;
        }

        .category:hover {
            color: #f8b600;

        }
    </style>
{% endblock %}
{% block body %}
    <!-- start banner Area -->
    <section class="banner-area relative blog-home-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content blog-header-content col-lg-12">
                    <h1 class="text-white">
                        Dude You’re Getting
                        a Telescope
                    </h1>
                    <p class="text-white">
                        There is a moment in the life of any aspiring astronomer that it is time to buy that first
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start top-category-widget Area -->
    <section class="top-category-widget-area pt-90 pb-90 ">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget1.jpg' %}"
                                         alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                                    <span></span>
                                    <p>Enjoy your social life together</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget2.jpg' %}"
                                         alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                                    <span></span>
                                    <p>Be a part of politics</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget3.jpg' %}"
                                         alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Food</h4>
                                    <span></span>
                                    <p>Let the food be finished</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End top-category-widget Area -->

    <!-- Start post-content Area -->
    <section class="post-content-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    {% for post in posts %}
                        <div class="single-post row">
                            <div class="col-lg-3  col-md-3 meta-details">
                                <ul class="tags">
                                    {% for cat in post.category.all %}
                                        <a class="category"
                                           href="{% url 'blog:blog_category' cat.name %}">{{ cat.name }}</a>
                                        {% if not forloop.last %},{% endif %}
                                    {% endfor %}

                                </ul>
                                <div class="user-details row">
                                    <p class="user-name col-lg-12 col-md-12 col-6"><a
                                            href="{% url 'blog:blog_author' post.author.username %}">{{ post.author.get_full_name }}</a>
                                        <span
                                                class="lnr lnr-user"></span></p>
                                    <p class="date col-lg-12 col-md-12 col-6"><a
                                            href="#">{{ post.published_date | date:'d M Y' }}</a>
                                        <span
                                                class="lnr lnr-calendar-full"></span></p>
                                    <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_views }}M
                                        Views</a> <span
                                            class="lnr lnr-eye"></span></p>
                                    <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{ post.count_comments }} comments</a> <span
                                            class="lnr lnr-bubble"></span></p>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 ">
                                <div class="feature-img">
                                    <img class="img-fluid" src="{{ post.image.url }}" alt="" style="height: 252px">
                                </div>
                                <a class="posts-title" href="{% url 'blog:blog_single' post.id %}"><h3>{{ post.title }}
                                </h3></a>
                                <p class="excert">
                                    {{ post.content |truncatewords:'50'|safe }}
                                </p>
                                <a href="{% url 'blog:blog_single' post.id %}" class="primary-btn">View More</a>
                            </div>
                        </div>
                    {% endfor %}
                    <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            {% if posts.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ posts.previous_page_number }}" class="page-link"
                                       aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for i in posts.paginator.page_range %}
                                {% if posts.number == i %}
                                    <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        <div class="single-sidebar-widget search-widget">
                            <form class="search-form" method="get" action="{% url 'blog:blog_search' %}">
                                <input placeholder="Search Posts" name="search" type="text"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        {% include 'blog/blog-writer.html' %}
                        {% include 'blog/blog-latest-posts.html' %}
                        <div class="single-sidebar-widget ads-widget">
                            <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
                        </div>
                        {% include 'blog/blog-post-category.html' %}
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->

{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in lasted_posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{ post.image.url }}" alt="" style="height: 60px;width: 80px">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_single' post.id %}"><h6>{{ post.title | truncatewords:3 }}</h6></a>
                <p>{{ post.published_date | timesince  }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-category.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,value in cat_dict.items %}
        <li>
            <a href="{% url 'blog:blog_category' name %}" class="d-flex justify-content-between">
                <p>{{ name }}</p>
                <p>{{ value }}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- start banner Area -->
    <section class="relative about-banner">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        {{ post.title }}
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span><a href="{% url 'blog:blog' %}">Blog </a> <span
                            class="lnr lnr-arrow-right"></span> {{ post.title }}
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start post-content Area -->
    <section class="post-content-area single-post-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="{{ post.image.url }}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-3  col-md-3 meta-details">
                            <ul class="tags">
                                <li><a href="#">Food,</a></li>
                                <li><a href="#">Technology,</a></li>
                                <li><a href="#">Politics,</a></li>
                                <li><a href="#">Lifestyle</a></li>
                            </ul>
                            <div class="user-details row">
                                <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author }}</a> <span
                                        class="lnr lnr-user"></span></p>
                                <p class="date col-lg-12 col-md-12 col-6"><a
                                        href="#">{{ post.published_date|date:"d M Y" }}</a> <span
                                        class="lnr lnr-calendar-full"></span></p>
                                <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_views }}M
                                    Views</a> <span
                                        class="lnr lnr-eye"></span></p>
                                <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{ comments.count }}
                                    comments</a> <span
                                        class="lnr lnr-bubble"></span></p>
                                <ul class="social-links col-lg-12 col-md-12 col-6">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-github"></i></a></li>
                                    <li><a href="#"><i class="fa fa-behance"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <h3 class="mt-20 mb-20">{{ post.title }}</h3>
                            <p class="excert">
                                {{ post.content | safe }}
                            </p>

                        </div>

                    </div>
                    <div class="navigation-area">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                <div class="thumb">
                                    <a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}"
                                                     alt=""></a>
                                </div>
                                <div class="arrow">
                                    <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                                </div>
                                <div class="detials">
                                    <p>Prev Post</p>
                                    <a href="#"><h4>Space The Final Frontier</h4></a>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                <div class="detials">
                                    <p>Next Post</p>
                                    <a href="#"><h4>Telescopes 101</h4></a>
                                </div>
                                <div class="arrow">
                                    <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                                </div>
                                <div class="thumb">
                                    <a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}"
                                                     alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="comments-area">
                        <h4>{{ comments.count }} comments</h4>
                        {% for comment in comments %}
                            <div class="comment-list">
                                <div class="single-comment justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">{{ comment.name }}</a></h5>
                                            <p class="date">{{ comment.created_date | timesince }}</p>
                                            <p class="comment">
                                                {{ comment.message }}
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="comment-form">
                        <h4>Leave a Comment</h4>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group ">

                                <input type="hidden" name="name" value="{{ request.user.username }}">
                                {% if request.user.email %}
                                    <input type="hidden" name="email" value="{{ request.user.email }}">
                                {% else %}
                                  
                                    <div class="form-group">
                                        <input type="email" class="form-control" name="email" placeholder="email"
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Enter email address'">
                                    </div>
                                {% endif %}


                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" placeholder="Subject"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
                                          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                                          required=""></textarea>
                            </div>
                            <button type="submit" class="primary-btn text-uppercase">Post Comment</button>
                        </form>
                    </div>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        <div class="single-sidebar-widget search-widget">
                            <form class="search-form" method="get" action="{% url 'blog:blog_search' %}">
                                {% csrf_token %}
                                <input placeholder="Search Posts" name="search" type="text"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        {% include 'blog/blog-writer.html' %}
                        {% include 'blog/blog-latest-posts.html' %}
                        <div class="single-sidebar-widget ads-widget">
                            <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
                        </div>
                        {% include 'blog/blog-post-category.html' %}

                        <div class="single-sidebar-widget tag-cloud-widget">
                            <h4 class="tagcloud-title">Tag Clouds</h4>
                            <ul>
                                {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:blog_tag' tag.name %}">{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->

{% endblock %}

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>davoudi</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you
        should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
        andits detractors.
    </p>
</div>